import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import { motion } from  'framer-motion';
import './styles/projectPagestyles.css';
import greentrips from '../Images/greentrips-img.jpg';


function Project1() {
    return (
    <Container fluid className='container-light profileSection'>
    <Container className='containerStyle'>
      <Row className='projectRow'>
        <Container className=''>
          <img src={greentrips} alt='greentrips' className='projectImg'></img>
          </Container>
        <Col className='projectCol'>
          <h1>PROJECT TITLE <span>LOREM IPSUM</span></h1>
          <p className='projectContent'>Toyota Green Trips is an innovative web application designed to promote sustainable transportation practices by providing users with valuable insights into the carbon emissions generated by their trips within Australia. By simply inputting their starting and destination locations, the app swiftly calculates the CO2 emissions associated with the journey, enabling individuals to make informed decisions about their transportation choices. With a focus on promoting eco-friendly travel, Toyota Green Trips empowers users to take proactive steps towards reducing their carbon footprint, ultimately contributing to a greener and more sustainable future for Australia.</p>
          <h4>Technologies</h4>
          <p>
            Javascript, Node JS, API, Express, MongoDB, Mongoose, React, React Router, 
          </p>
          <h4 href="">View on Github</h4>
          <a className='buttonDark' href="/">Back to Home</a>
        <Row className='projectRow'>
        </Row>
        </Col>
        </Row>
    </Container>
  </Container>
    )
}

export default Project1;